In [1]:
from gssutils import *
from databaker.framework import *
import pandas as pd
import datetime

def left(s, amount):
    return s[:amount]

def right(s, amount):
    return s[-amount:]

def mid(s, offset, amount):
    return s[offset:offset+amount]

year = right(str(datetime.datetime.now().year),2)

scraper = Scraper('https://www.gov.uk/government/statistics/family-resources-survey-financial-year-201718')
dist = scraper.distribution(title=lambda t: 'Disability data tables (XLS)' in t)
tab = next(t for t in dist.as_databaker() if t.name == '4_1')

In [2]:
tidied_sheets = []
        
cell = tab.filter("Year")
    
year = cell.shift(RIGHT).expand(DOWN).is_not_blank().shift(LEFT)

remove = tab.filter("Sample size").expand(DOWN)

age = cell.shift(RIGHT).expand(RIGHT).is_not_blank() - remove

observations = year.shift(RIGHT).expand(RIGHT).is_not_blank() - remove

dimensions = [
        #HDimConst('Dimension Name', 'Variable'),
        HDim(year, 'Period', DIRECTLY, LEFT), 
        HDim(age, 'Age Group', DIRECTLY, ABOVE),
        HDimConst('Measure type','Percentage'),
        HDimConst('Unit','People')    
]
    
c1 = ConversionSegment(observations, dimensions, processTIMEUNIT=True)
savepreviewhtml(c1, fname="Preview.html")

tablepart '4_1' written #injblock1001
javascript calculated

C:\Users\Red\Documents\COGS\Disability\DWP-Family-Resources-Survey-Disability\Preview.html

In [3]:
new_table = c1.topandas()
import numpy as np
new_table['OBS'].replace('', np.nan, inplace=True)
new_table.dropna(subset=['OBS'], inplace=True)
new_table.rename(columns={'OBS': 'Value'}, inplace=True)
new_table['Value'] = new_table['Value'].astype(int)
new_table['Period'] = new_table['Period'].map(
    lambda x: f'gregorian-interval/{left(x,2) + right(x,2)}-03-31T00:00:00/P1Y')
new_table['Age Group'] = new_table['Age Group'].map(
    lambda x: left(x, len(x) - 1) if x.endswith('1') else x)
new_table = new_table[['Period','Age Group','Measure type','Value','Unit']]
new_table

,Period,Age Group,Measure type,Value,Unit
4,gregorian-interval/2008-03-31T00:00:00/P1Y,All people,Percentage,18,People
5,gregorian-interval/2008-03-31T00:00:00/P1Y,Working-age adults,Percentage,14,People
6,gregorian-interval/2008-03-31T00:00:00/P1Y,State Pension age adults,Percentage,46,People
7,gregorian-interval/2008-03-31T00:00:00/P1Y,Children,Percentage,6,People
8,gregorian-interval/2009-03-31T00:00:00/P1Y,All people,Percentage,19,People
9,gregorian-interval/2009-03-31T00:00:00/P1Y,Working-age adults,Percentage,14,People
10,gregorian-interval/2009-03-31T00:00:00/P1Y,State Pension age adults,Percentage,47,People
11,gregorian-interval/2009-03-31T00:00:00/P1Y,Children,Percentage,6,People
12,gregorian-interval/2010-03-31T00:00:00/P1Y,All people,Percentage,19,People
13,gregorian-interval/2010-03-31T00:00:00/P1Y,Working-age adults,Percentage,15,People
14,gregorian-interval/2010-03-31T00:00:00/P1Y,State Pension age adults,Percentage,45,People
15,gregorian-interval/2010-03-31T00:00:00/P1Y,Children,Percentage,6,People
16,gregorian-interval/2011-03-31T00:00:00/P1Y,All people,Percentage,19,People
17,gregorian-interval/2011-03-31T00:00:00/P1Y,Working-age adults,Percentage,15,People
18,gregorian-interval/2011-03-31T00:00:00/P1Y,State Pension age adults,Percentage,45,People
19,gregorian-interval/2011-03-31T00:00:00/P1Y,Children,Percentage,6,People
20,gregorian-interval/2012-03-31T00:00:00/P1Y,All people,Percentage,19,People
21,gregorian-interval/2012-03-31T00:00:00/P1Y,Working-age adults,Percentage,16,People
22,gregorian-interval/2012-03-31T00:00:00/P1Y,State Pension age adults,Percentage,45,People
23,gregorian-interval/2012-03-31T00:00:00/P1Y,Children,Percentage,6,People
24,gregorian-interval/2013-03-31T00:00:00/P1Y,All people,Percentage,19,People
25,gregorian-interval/2013-03-31T00:00:00/P1Y,Working-age adults,Percentage,16,People
26,gregorian-interval/2013-03-31T00:00:00/P1Y,State Pension age adults,Percentage,43,People
27,gregorian-interval/2013-03-31T00:00:00/P1Y,Children,Percentage,7,People
28,gregorian-interval/2014-03-31T00:00:00/P1Y,All people,Percentage,19,People
29,gregorian-interval/2014-03-31T00:00:00/P1Y,Working-age adults,Percentage,16,People
30,gregorian-interval/2014-03-31T00:00:00/P1Y,State Pension age adults,Percentage,42,People
31,gregorian-interval/2014-03-31T00:00:00/P1Y,Children,Percentage,7,People
32,gregorian-interval/2015-03-31T00:00:00/P1Y,All people,Percentage,20,People
33,gregorian-interval/2015-03-31T00:00:00/P1Y,Working-age adults,Percentage,17,People
34,gregorian-interval/2015-03-31T00:00:00/P1Y,State Pension age adults,Percentage,45,People
35,gregorian-interval/2015-03-31T00:00:00/P1Y,Children,Percentage,7,People
36,gregorian-interval/2016-03-31T00:00:00/P1Y,All people,Percentage,21,People
37,gregorian-interval/2016-03-31T00:00:00/P1Y,Working-age adults,Percentage,18,People
38,gregorian-interval/2016-03-31T00:00:00/P1Y,State Pension age adults,Percentage,44,People
39,gregorian-interval/2016-03-31T00:00:00/P1Y,Children,Percentage,7,People
40,gregorian-interval/2017-03-31T00:00:00/P1Y,All people,Percentage,22,People
41,gregorian-interval/2017-03-31T00:00:00/P1Y,Working-age adults,Percentage,19,People
42,gregorian-interval/2017-03-31T00:00:00/P1Y,State Pension age adults,Percentage,45,People
43,gregorian-interval/2017-03-31T00:00:00/P1Y,Children,Percentage,8,People
44,gregorian-interval/2018-03-31T00:00:00/P1Y,All people,Percentage,21,People
45,gregorian-interval/2018-03-31T00:00:00/P1Y,Working-age adults,Percentage,18,People
46,gregorian-interval/2018-03-31T00:00:00/P1Y,State Pension age adults,Percentage,44,People
47,gregorian-interval/2018-03-31T00:00:00/P1Y,Children,Percentage,8,People

In [44]:
destinationFolder = Path('out')
destinationFolder.mkdir(exist_ok=True, parents=True)

TAB_NAME = 'Disability-prevalence-by-age-group-2007-08-to-2017-18'

new_table.drop_duplicates().to_csv(destinationFolder / f'{TAB_NAME}.csv', index = False)